FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY money_rain.py .

# Pre-install script dependencies
RUN uv export --script money_rain.py --format requirements-txt > requirements.txt && \
    uv pip install --system -r requirements.txt

CMD ["python", "money_rain.py"]