FROM python:3.12-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY check_rain .

# Pre-install script dependencies
RUN sed -i '1d' check_rain && \
    uv export --script check_rain --format requirements-txt > requirements.txt && \
    uv pip install --system -r requirements.txt

CMD ["python", "check_rain"]