[project]
name = "microbe-in-flask"
version = "0.1.0"
requires-python = ">=3.12.3"
dependencies = [
    "flask==0.11.1",
    "requests>=2.32.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[tool.pytest.ini_options]
testpaths = ["tests", "integration"]
