name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [ "CI" ]
    types: [ completed ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Lektor
        run: pip install lektor

      - name: Build site
        working-directory: kutubuku
        run: lektor build --output-path ./public

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: kutubuku/public
          branch: gh-pages
          clean: true
